/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "on-tertiary": "#402d00",
        "tertiary-container": "#b88900",
        "surface-container-high": "#262a30",
        "error-container": "#93000a",
        "primary": "#60a5fa",
        "on-primary-container": "#dbeafe",
        "on-background": "#e0e2ea",
        "on-error": "#690005",
        "on-secondary": "#2b313a",
        "inverse-surface": "#e0e2ea",
        "on-secondary-container": "#b0b5c1",
        "on-error-container": "#ffdad6",
        "surface-container-lowest": "#03060a",
        "surface-container-highest": "#1c2028",
        "secondary-container": "#414751",
        "on-primary-fixed-variant": "#1e40af",
        "tertiary-fixed": "#ffdf9f",
        "tertiary": "#f9bd22",
        "primary-fixed": "#93c5fd",
        "on-primary-fixed": "#1e3a8a",
        "secondary-fixed": "#dde3ef",
        "on-surface": "#e0e2ea",
        "surface-tint": "#60a5fa",
        "background": "#070a0d",
        "surface-container": "#0f1318",
        "inverse-primary": "#1e3a8a",
        "surface-bright": "#272b32",
        "primary-container": "#1d4ed8",
        "on-secondary-fixed-variant": "#414751",
        "outline": "#8b90a0",
        "surface-dim": "#070a0d",
        "on-tertiary-container": "#372700",
        "on-tertiary-fixed-variant": "#5c4300",
        "surface": "#070a0d",
        "secondary-fixed-dim": "#c1c7d3",
        "outline-variant": "#414755",
        "error": "#ffb4ab",
        "on-tertiary-fixed": "#261a00",
        "secondary": "#c1c7d3",
        "on-primary": "#dbeafe",
        "surface-container-low": "#0c0f14",
        "inverse-on-surface": "#2d3136",
        "on-secondary-fixed": "#161c25",
        "primary-fixed-dim": "#60a5fa",
        "surface-variant": "#1c2028",
        "on-surface-variant": "#c1c6d7",
        "tertiary-fixed-dim": "#f9bd22",
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px",
      },
      fontFamily: {
        headline: ["Manrope", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
      keyframes: {
        float: {
          "0%, 100%": { transform: "translateY(0)" },
          "50%": { transform: "translateY(-16px)" },
        },
        "fade-in-up": {
          "0%": { opacity: "0", transform: "translateY(16px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        marquee: {
          "0%": { transform: "translateX(0)" },
          "100%": { transform: "translateX(-50%)" },
        },
      },
      animation: {
        float: "float 6s ease-in-out infinite",
        "fade-in-up": "fade-in-up 0.7s ease-out both",
        marquee: "marquee 110s linear infinite",
      },
    },
  },
  plugins: [],
};
